export const LOGIN_SUCCESS = "Login/LOGIN_SUCESS";
export const LOGIN_ERROR = "Login/LOGIN_ERROR";

export const EMPLOYEES_LOADED = "Employees/EMPLOYEES_LOADED";
export const EMPLOYEES_LOADING = "Employees/EMPLOYEES_LOADING";
export const EMPLOYEES_LOADING_ERROR = "Employees/EMPLOYEES_LOADING_ERROR";

export const EMPLOYEE_CREATED = "Employees/EMPLOYEE_CREATED";
